logging:
  file:
    path: logs/
  level:
    '[org.springframework.data]': TRACE
    '[org.hibernate]': TRACE
    '[javax.persistence]': TRACE
    root: info

  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
