server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: ms-user
  main:
    allow-bean-definition-overriding: true
  profiles:
    active:
      - db
      - logger