spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_POSTGRE_HOST:localhost}:${DB_POSTGRE_PORT:5432}/postgres?currentSchema=msuser&createDatabaseIfNotExist=true&useUnicode=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_POSTGRE_USER:postgres}
    password: ${DB_POSTGRE_PASSWORD:root}
    hikari:
      minimum-idle: 60000
      maximum-pool-size: 5
      pool-name: HikariUserCP
      connectionTimeout: 30000
      connection-test-query: SELECT 1
    tomcat:
      test-while-idle: true
      validation-query: 1

  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            database:
              action: create
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        generate_statistics: false
        jdbc:
          fetch_size: 2000
          lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create
        hbm2dll:
          create_namespaces: true
        default_schema: msuser
